Repository vrk-kpa/suomifi-icons, pull requests merged in 2020-05, with the labels that each got.

#32 [Feature] Improvements for toggle icon to align with style guide
  src/componentIcons/icon-toggle.svg
Labels: enhancement

#33 [Release] 0.1.2
  package.json
Labels: release

#34 [Fix] Updated the required peerDependencies to lower version
  package.json
Labels: bug
