Repository vrk-kpa/suomifi-icons, pull requests merged in 2020-11, with the labels that each got.

#43 [Feature] Calendar checked icon and update for link external icon
  package.json
  src/baseIcons.ts
  src/baseIcons/icon-calendar-checked.svg
  src/baseIcons/icon-link-external.svg
  yarn.lock
Labels: dependencies, enhancement

#44 [Release] 1.1.0
  package.json
Labels: release

#45 [Fix]Old browser support
  webpack.config.js
Labels: bug

#46 [Release] 1.1.1
  package.json
Labels: release
